version: '3.9'
services:
  collector:
    image: otel/opentelemetry-collector:0.50.0
    container_name: collector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317" # otlp grpc
      - "4318:4318" # otlp http
      - "13133:13133" # health_check
    depends_on:
      - jaeger
      - zipkin
  
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  dd-agent:
    image: "datadog/agent:latest"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    environment:
      - DD_APM_ENABLED=true
      - DD_API_KEY=${DD_API_KEY}
      - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT=0.0.0.0:4317
      - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_HTTP_ENDPOINT=0.0.0.0:4318
      - DD_OTLP_CONFIG_METRICS_ENABLED=true
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      # - DD_OTLP_CONFIG_METRICS_INSTRUMENTATION_SCOPE_METADATA_AS_TAGS=true
    ports:
      - "4317:4317"
      - "4318:4318"
