receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:
    timeout: 5s

exporters:
  logging:
    logLevel: debug
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
  jaeger:
    endpoint: "jaeger:14250"
    tls:
      insecure: true

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging,zipkin,jaeger]
